---
include:
  - board: nice_nano_v2
    shield: dactyl_left
    artifact-name: dactyl_left
  - board: nice_nano_v2
    shield: dactyl_right
    artifact-name: dactyl_right
  - board: nice_nano_v2
    shield: dactyl_test_left
    artifact-name: dactyl_test_left
  - board: nice_nano_v2
    shield: dactyl_test_right
    artifact-name: dactyl_test_right
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: settings_reset
